### PR TITLE
chore(feat): Update regctl to copy multi-arch image to different registry - SAAS-1953

### PR DESCRIPTION
**Pull request by brownnguyen-armory**

### CODE REVIEW

**Review by edgarulg — APPROVED** [review]
LGTM, Just make sure you backport this change to release-2.31.x only

**Comment by edgarulg** [comment]
Mergify is not enabled in this repository so you need to do the cherry pick manually to the release branch

**Comment by edgarulg** [comment]
@brownnguyen-armory Also don't forget to validate the multi arch images are published correctly to Artifactory from the extension projects because this GHA is expecting those images are published.

**Comment by brownnguyen-armory** [comment]
Verified, the image pushed to Artifactory with AMD, and Dockerhub with both ARM and AMD.

**Review by christosarvanitis — APPROVED** [review]

**Pull request merged**
